# https://docs.github.com/en/actions/learn-github-actions/variables

name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'jjehring/MavenBuild'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats

